language: java
dist: trusty
sudo: false
jdk:
  - openjdk8
env:
  - GH_URL=https://raw.githubusercontent.com VALIDATOR_URL=https://validator.swagger.io/validator/debug?url FILE_TO_VALIDATE=api.yaml URL_TO_VALIDATE=$GH_URL/${TRAVIS_PULL_REQUEST_SLUG:-$TRAVIS_REPO_SLUG}/${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}/docs/$FILE_TO_VALIDATE

script:
  # validate
  - echo "Validating $URL_TO_VALIDATE:"
  - VALIDATION_OUTPUT=`curl -sS "$VALIDATOR_URL=$URL_TO_VALIDATE"`

  # print validation errors
  - echo $VALIDATION_OUTPUT

  # check if the validation output ignoring warnings is an empty array
  - VALIDATION_ERROR_COUNT=`echo "$VALIDATION_OUTPUT" |jq -c '.schemaValidationMessages // [] | map(select(.level != "warning"))' |jq length`
  - test "$VALIDATION_ERROR_COUNT" == 0
