language: node_js
node_js:
  - lts/*
services:
  - mongodb
env:
  - GH_URL=https://raw.githubusercontent.com PATH_TO_VALIDATE=$GH_URL/${TRAVIS_PULL_REQUEST_SLUG:-$TRAVIS_REPO_SLUG}/${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} API_PATH=docs/api.yaml
install:
  npm install -g swagger-cli
  npm install jest
  npm install supertest
  npm install
script:
  # validate apis
  - echo "Validating $PATH_TO_VALIDATE/API_PATH:"
  - API_VALIDATION_OUTPUT=`swagger-cli validate $PATH_TO_VALIDATE/$API_PATH`

  - echo $API_VALIDATION_OUTPUT

  # run node tests
  - npm run test

